apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea-service-broker.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gitea-service-broker.name" . }}
    helm.sh/chart: {{ include "gitea-service-broker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  USERNAME: {{ required ".Values.config.username is required" .Values.config.username | b64enc | quote }}
  PASSWORD: {{ required ".Values.config.password is required" .Values.config.password | b64enc | quote }}
  GITEA_URL: {{ required ".Values.config.giteaURL is required" .Values.config.giteaURL | b64enc | quote }}
  GITEA_ADMIN_ACCESS_TOKEN: {{ required ".Values.config.giteaToken is required" .Values.config.giteaToken | b64enc | quote }}
  GITEA_ADMIN_USERNAME: {{ required ".Values.config.giteaUsername is required" .Values.config.giteaUsername | b64enc | quote }}
